### ISSUE TITLE
Train on Another Data Set

### ISSUE THREAD

**Issue by ahkarami** [zisianw/FaceBoxes.PyTorch#15]
@zisianw, 
Thank you for your nice work. I have two questions:
1) Can one train your model (with the provided training code) on another data set, with different aspect ratio for anchor boxes? (If yes, please explain how we can do that.)
2) Have you ever trained this model for pedestrian detection (for example on Caltech data set)? [If no, do you have a future plan for it?]

Thank you very much

**Comment by zisianw** [comment]
Hi @ahkarami, thank you. This work was aimed to reproduce FaceBoxes in PyTorch which was originally implemented in Caffe. Therefore, we do not plan to train the model on other datasets. However, since training code is released, one can modify the codes and train it on another dataset. As you have pointed out, the implementation in FaceBoxes only consider square anchor boxes. To change the aspect ratios, you could refer to [ssd version](https://github.com/amdegroot/ssd.pytorch/blob/master/layers/functions/prior_box.py) which covers different aspect ratio.

**Comment by ahkarami** [comment]
@zisianw,
Thank you for your helpful response.
