### ISSUE TITLE
make errer

### ISSUE THREAD

**Issue by ruiming46zrm** [zisianw/FaceBoxes.PyTorch#28]
error when running ./make.sh, any methods ？ :
           ^
nms/cpu_nms.c: In function ‘__Pyx__GetException’:
nms/cpu_nms.c:8961:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                      ^
nms/cpu_nms.c:8962:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                       ^
nms/cpu_nms.c:8963:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                    ^
nms/cpu_nms.c:8964:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = local_type;
           ^
nms/cpu_nms.c:8965:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = local_value;
           ^
nms/cpu_nms.c:8966:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = local_tb;
           ^
error: command 'gcc' failed with exit status 1

**Comment by zisianw** [comment]
Hi @ruiming46zrm, I have not faced this before, but based on some discussion on the internet, it seems to be related to Cython. Could you try to install Cython e.g. `$ sudo pip install cython` and see if it solves the problem?

**Comment by lxy5513** [comment]
Hi @zisianw  , 

I met the problem too, although I install cython, the error is still exist.

**Comment by lxy5513** [comment]
I solved by create a new conda env

**Comment by WangZaili** [comment]
Hi @ruiming46zrm @lxy5513 ,
This problem is due to some confliction between latent Cython and Python3.7. See
https://github.com/cython/cython/issues/1955
This issue had been solved in newer Cython. So upgrading or installing newest version Cython can solve the issue.
But in the repo @zisianw provided cpu_nms.c and gpu_nms.cpp generated by older version Cython (0.25.2, see line 1 in the files). Cython would not re-generate this files but when compiling them the error occurs.
So you can simply delete the "*pu_nms.*" files so that they can be generated by latest Cython and the compiler will be happy.
