### ISSUE TITLE
Why the input size for training only supports 1024?

### ISSUE THREAD

**Issue by li3cmz** [zisianw/FaceBoxes.PyTorch#57]
https://github.com/zisianw/FaceBoxes.PyTorch/blob/c115c594d6417e9d364252d6eae90b1788be54c8/train.py#L34

**Comment by xsacha** [comment]
The box encoding is only done for 1024 resolution. You could generate one dynamically based on width and height, the same way the decoding one is done if you like.
Training images are typically a standard size and I don't think this affects accuracy at all.

**Comment by li3cmz** [comment]
I can't find why “The box encoding is only done for 1024 resolution. ”
Could you tell me where it is embodied in the code? Thank you very much!

**Comment by xsacha** [comment]
Sorry, it's not hardcoded anymore. It was fixed in https://github.com/zisianw/FaceBoxes.PyTorch/commit/d065b47b8a794e97fb0326961c0929a7ada85036

The prior box is generated here: https://github.com/zisianw/FaceBoxes.PyTorch/blob/79d6466264df69406529a9e164f310a8c6eaafdf/train.py#L78
So changing img_dim to your desired width and height will work.

If you encounter any issues with the backward pass of the model, you can change the MaxPool's to AdaptiveMaxPool.

**Comment by li3cmz** [comment]
Oh, I get it. Thank you very much~
