### ISSUE TITLE
train speed.

### ISSUE THREAD

**Issue by yyfyan** [zisianw/FaceBoxes.PyTorch#9]
你好，我在训练该代码时发现，每隔几次迭代，会出现卡顿。为什么会出现这种情况，你训练时有遇到类似情况吗？我的pytorch版本是0.4.1。

**Comment by zisianw** [comment]
@yyfyan, yes it is same on our side. I believe this is due to the pre-processing of training images as the cropping step in data augmentation needs to go through multiple run until a suitable patch is obtained. See [here](https://github.com/zisianw/FaceBoxes.PyTorch/blob/master/data/data_augment.py#L7).

**Comment by yyfyan** [comment]
@zisianw，OK,thanks.
